main: nl.thedutchmc.haro_torch.plugin.HaroTorch
name: Haro_Torch
author: TheDutchMC76
version: 1.0
description: Adds Haro's Torch, a tool which disables mob spawns
commands:
 ht:
  usage: /ht <option>
  description: Haros Torch base command
 stc:
  usage: /stc
  description: Later maybe
